opt:
 sassin: ./assets/build/sass
 sasspartials: ./assets/build/partials
 sassout: ./assets/build/css
 cssin: ./assets/build/css
 cssout: ./assets/optimized/css/min3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333740cdd0edad3d26f1.css
 jsin: ./assets/build/js
 jsout: ./assets/optimized/js/min33333333333333333333333333333333333333333333333333333333333333333333333333333333333333331d460f4.js
 imgin: ./assets/optimized/img